=== codes-abdullah/RGenerator/src/main/resources/rit/R.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="codes.abdullah.rit" xmlns:xs="codes.abdullah.rit"
	elementFormDefault="qualified">


	<complexType name="string-type">
		<simpleContent>
			<extension base="string">
				<attribute name="name" type="string" use="required"></attribute>
			</extension>
		</simpleContent>
	</complexType>

	<complexType name="string-array-type">
		<sequence>
			<element type="string" name="item" minOccurs="0"
				maxOccurs="unbounded">
			</element>
		</sequence>
		<attribute name="name" type="string" use="required"></attribute>
	</complexType>

	<complexType name="import-type">
		<simpleContent>
			<extension base="string">
			</extension>
		</simpleContent>
	</complexType>

	<complexType name="include-strings-type">
		<simpleContent>
			<extension base="string">
				<attribute name="file" use="required"></attribute>
			</extension>
		</simpleContent>
	</complexType>


	<complexType name="path-type">
		<simpleContent>
			<extension base="string">
				<attribute name="name" use="required"></attribute>
			</extension>
		</simpleContent>
	</complexType>


	<complexType name="resource-paths-type">
		<annotation>
			<documentation>
				Generate paths to resource files in the project
			</documentation>
		</annotation>
		<simpleContent>
			<extension base="string">
				<attribute name="root-dir" use="required" type="string">
					<annotation>
						<documentation>
							Root dir to start search from, must be relative to
							application root dir, e.g: src/main/resources
						</documentation>
					</annotation>
				</attribute>
				<attribute name="matcher-pattern" use="optional"
					type="string" default="glob:**">
					<annotation>
						<documentation>
							pattern for java.nio.file.PathMatcher, must start
							with (glob:) or (regex:)
						</documentation>
					</annotation>
				</attribute>
				<!-- <attribute name="extensions" use="optional" type="string"> <annotation> 
					<documentation> Specific extensions separated by comma to search for files, 
					or * for wildcard, e.g: jpeg,png,xml </documentation> </annotation> </attribute> -->


				<attribute name="join-mode" use="optional"
					default="JOIN_NAME" type="string">
					<annotation>
						<documentation>
							How to create declared field names, e.g:
							mode(JOIN_EXT_DIR_NAME), path(imgs/splash.jpeg), result field
							name: (JPEG_IMGS_SPLASH), available modes are:
							[JOIN_NAME|JOIN_EXT_NAME|JOIN_DIR_NAME|JOIN_EXT_DIR_NAME]
						</documentation>
					</annotation>
				</attribute>

				<attribute name="relative-paths" use="optional"
					type="boolean">
					<annotation>
						<documentation>
							If relative-paths=true, and relative-paths-to is empty, will insert (.)
							before the path, e.g:
							/error.jsp -> ./error.jsp, otherwise if relative-paths=true
							and relative-paths-to not empty, will insert (relative-paths-to) e.g:
							/error.jsp -> dev/jee/jsps/error.jsp
						</documentation>
					</annotation>
				</attribute>

				<attribute name="relative-paths-to" use="optional"
					type="boolean">
					<annotation>
						<documentation>
							If relative-paths=true, and relative-paths-to is empty, will insert (.)
							before the path, e.g:
							/error.jsp -> ./error.jsp, otherwise if relative-paths=true
							and relative-paths-to not empty, will insert (relative-paths-to) e.g:
							/error.jsp -> dev/jee/jsps/error.jsp
						</documentation>
					</annotation>
				</attribute>




				<attribute name="max-depth" use="optional"
					type="nonNegativeInteger" default="2147483647">
					<annotation>
						<documentation>
							Max depth to search in subdirs
						</documentation>
					</annotation>
				</attribute>


			</extension>
		</simpleContent>
	</complexType>

	<complexType name="pair-type">
		<simpleContent>
			<extension base="string">
				<attribute name="key" type="string" use="required">
					<annotation>
						<documentation>The pair key, by default will be capitalized
						</documentation>
					</annotation>
				</attribute>
				<attribute name="type" type="string" use="optional">
					<annotation>
						<documentation>Override default value type, default is
							java.lang.String
						</documentation>
					</annotation>
				</attribute>
			</extension>
		</simpleContent>
	</complexType>

	<complexType name="key-type">
		<simpleContent>
			<extension base="string">
				<attribute name="key" type="string" use="optional">
					<annotation>
						<documentation>Override default key name, default name is the
							value capitalized
						</documentation>
					</annotation>
				</attribute>
				<attribute name="type" type="string" use="optional">
					<annotation>
						<documentation>Override default type, default is
							java.lang.String
						</documentation>
					</annotation>
				</attribute>
			</extension>
		</simpleContent>
	</complexType>


	<complexType name="array-type">
		<sequence>
			<element type="string" name="item" minOccurs="0"
				maxOccurs="unbounded">
			</element>
		</sequence>
		<attribute name="name" type="string" use="required"></attribute>
		<attribute name="type" type="string" use="optional"></attribute>
	</complexType>





	<complexType name="class-type">
		<sequence>
			<choice maxOccurs="unbounded">
				<element type="xs:pair-type" name="pair" minOccurs="0"
					maxOccurs="unbounded">
				</element>
				<element type="xs:class-type" name="class" minOccurs="0"
					maxOccurs="unbounded">
				</element>
				<element type="xs:key-type" name="key" minOccurs="0"
					maxOccurs="unbounded">
				</element>
				<element type="xs:array-type" name="array" minOccurs="0"
					maxOccurs="unbounded">
				</element>
				<element type="xs:path-type" name="path" minOccurs="0"
					maxOccurs="unbounded">
				</element>
				<element type="xs:string-type" name="string" minOccurs="0"
					maxOccurs="unbounded">
				</element>
				<element type="xs:string-array-type" name="string-array"
					minOccurs="0" maxOccurs="unbounded">
				</element>
				<element type="xs:include-strings-type"
					name="include-strings" minOccurs="0" maxOccurs="unbounded">
				</element>
				<element type="xs:resource-paths-type" name="resource-paths"
					minOccurs="0" maxOccurs="unbounded">
				</element>
			</choice>
		</sequence>
		<attribute name="name" type="string" use="required"></attribute>
		<attribute name="modifiers" type="string"
			default="public static">
			<annotation>
				<documentation>
					Specify the modifiers
				</documentation>
			</annotation>
		</attribute>
	</complexType>




	<element name="R">
		<complexType>
			<sequence>
				<element type="xs:import-type" name="import"
					maxOccurs="unbounded" minOccurs="0"></element>
				<choice maxOccurs="unbounded">
					<element type="xs:class-type" name="class"
						maxOccurs="unbounded" minOccurs="0"></element>
					<element type="xs:pair-type" name="pair"
						maxOccurs="unbounded" minOccurs="0"></element>
					<element type="xs:key-type" name="key" minOccurs="0"
						maxOccurs="unbounded">
					</element>
					<element type="xs:array-type" name="array"
						maxOccurs="unbounded" minOccurs="0"></element>
					<element type="xs:path-type" name="path" minOccurs="0"
						maxOccurs="unbounded">
					</element>
					<element type="xs:string-type" name="string" minOccurs="0"
						maxOccurs="unbounded">
					</element>
					<element type="xs:string-array-type" name="string-array"
						minOccurs="0" maxOccurs="unbounded">
					</element>
					<element type="xs:include-strings-type"
						name="include-strings" minOccurs="0" maxOccurs="unbounded">
					</element>
					<element type="xs:resource-paths-type"
						name="resource-paths" minOccurs="0" maxOccurs="unbounded">
					</element>
				</choice>
			</sequence>

			<attribute name="R-class-package" type="string"
				use="optional">
				<annotation>
					<documentation>The package statement for R class</documentation>
				</annotation>
			</attribute>
			<attribute name="Rjsp-class-package" type="string"
				use="optional">
				<annotation>
					<documentation>The package statement for Rjsp class</documentation>
				</annotation>
			</attribute>
			<attribute name="modifiers" type="string" default="public"></attribute>
			<attribute name="R-class-generate" use="required"
				type="boolean"></attribute>
			<attribute name="R-class-outputDir" use="required"
				type="string"></attribute>

			<attribute name="Rjsp-class-generate" use="optional"
				type="boolean"></attribute>
			<attribute name="Rjsp-class-outputDir" use="optional"
				type="string"></attribute>


			<attribute name="Rjs-script-generate" use="optional"
				type="boolean"></attribute>
			<attribute name="Rjs-script-outputDir" use="optional"
				type="string"></attribute>

			<attribute type="boolean"
				name="properties-strings-generate" use="optional" default="false">
				<annotation>
					<documentation>Boolean to indicate wither .properties files should
						be generated or not
					</documentation>
				</annotation>
			</attribute>
			<attribute type="string"
				name="properties-strings-outputDir" use="optional">
				<annotation>
					<documentation>The output dir for .properties files, must be
						relative to app-
					</documentation>
				</annotation>
			</attribute>
			<attribute type="string"
				name="properties-strings-output-encoding" use="optional"
				default="iso-8859-1">
				<annotation>
					<documentation>The output encoding for .properties files
					</documentation>
				</annotation>
			</attribute>


		</complexType>

	</element>

</schema>

=== codes-abdullah/RGenerator/src/test/resources/rit/R.xml
<?xml version="1.0" encoding="UTF-8"?>
<R xmlns="codes.abdullah.rit" modifiers="public"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="codes.abdullah.rit ../../../../src/main/resources/rit/R.xsd "
	R-class-generate="true" R-class-package="codes.abdullah.r"
	Rjsp-class-package="codes.abdullah.r"
	R-class-outputDir="${project.build.testSourceDirectory}/codes/abdullah/r"
	Rjsp-class-generate="true"
	Rjsp-class-outputDir="${project.build.testSourceDirectory}/codes/abdullah/r"
	Rjs-script-generate="true" Rjs-script-outputDir="${project.build.testWebappDirectory}/js"
	properties-strings-generate="true"
	properties-strings-outputDir="${project.build.testResourceDirectory}/strings"
	properties-strings-output-encoding="iso-8859-1">

	<import>java.nio.file.*</import>
	<import>java.applet.Applet</import>
	<import>java.lang.CharSequence</import>

	
	<resource-paths root-dir="${project.build.testResourceDirectory}"
		matcher-pattern="glob:**/imgs/**/*.png" join-mode="JOIN_EXT_DIR_NAME"
		max-depth="2147483647" relative-paths="false">
	</resource-paths>
	
	
	<resource-paths root-dir="../"
		matcher-pattern="glob:**/imgs/**/*.jpg" join-mode="JOIN_EXT_DIR_NAME"
		max-depth="2147483647" relative-paths="false">
	</resource-paths>
	
		<resource-paths root-dir="."
		matcher-pattern="glob:**/imgs/**/*.jpg" join-mode="JOIN_EXT_DIR_NAME"
		max-depth="2147483647" relative-paths="false">
	</resource-paths>
	
		<resource-paths root-dir="inimg"
		matcher-pattern="glob:**/imgs/**/*.jpg" join-mode="JOIN_EXT_DIR_NAME"
		max-depth="2147483647" relative-paths="false">
	</resource-paths>


	<class name="jsps" modifiers="public static">
		<resource-paths root-dir="${project.build.testWebappDirectory}"
			join-mode="JOIN_NAME" matcher-pattern="glob:**/*.jsp"></resource-paths>
	</class>
	
	




	<class name="consts" modifiers="public static">
		<pair key="default_db_args">create=true;</pair>
		<pair key="default_db_dialect">org.hibernate.dialect.DerbyTenSevenDialect</pair>
		<pair key="default_db_driver">org.apache.derby.jdbc.ClientDriver</pair>
		<pair key="default_db_host">localhost</pair>
		<pair key="default_db_port" type="int">1527</pair>
		<pair key="default_db_schema">jdbc:derby</pair>
		<pair key="default_db_username">root</pair>
		<pair key="default_display_rows_per_page" type="int">5</pair>
		<pair key="default_redirect_after_seconds" type="int">5</pair>
		<pair key="default_servlet_session_timeout_secounds" type="int">60</pair>
		<pair key="default_verification_token_expiration_minutes">1</pair>
		<pair key="default_verification_token_length" type="int">20</pair>
		<pair key="dont_redirect" type="int">-1</pair>
		<pair key="email_regex_pattern">[a-z0-9._%+\\-]+@[a-z0-9.\\-]+</pair>
		<pair key="password_regex_pattern">^[a-zA-Z0-9!#@&amp;\\(\\).]{8,20}$</pair>
		<pair key="username_regex_pattern">^[a-zA-Z0-9_]{4,10}$</pair>
		<pair key="default_db_password"></pair>

	</class>



	<class name="strings" modifiers="public static">
		<include-strings file="${project.build.testResourceDirectory}/rit/strings.xml"></include-strings>
	</class>

	<class name="keys" modifiers="public static">
		<key>dbd</key>
		<key>display_rows_count</key>
		<key>include_page</key>
		<key>invalid_password</key>
		<key>message</key>
		<key>password</key>
		<key>redirect_after</key>
		<key>referer</key>
		<key>test_url</key>
		<key>test_url_result</key>
		<key>title</key>
		<key>url</key>
		<key>user</key>
		<key>user_id</key>
		<key>username</key>
		<key>users</key>
		<key>verification_tokens</key>
		<key>verified</key>
		<key>warning_message</key>
		<key>warning_messages</key>
		<key>warning_title</key>

		<pair key="jpa_driver">jakarta.persistence.jdbc.driver</pair>
		<pair key="jpa_password">jakarta.persistence.jdbc.password</pair>
		<pair key="jpa_url">jakarta.persistence.jdbc.url</pair>
		<pair key="jpa_user">jakarta.persistence.jdbc.user</pair>
	</class>


	<class name="arrays" modifiers="public static">
		<array name="jdbc_url_form_parts">
			<item>db_driver</item>
			<item>db_schema</item>
			<item>db_host</item>
			<item>db_port</item>
			<item>db_name</item>
			<item>db_args</item>
			<item>db_username</item>
			<item>db_password</item>
		</array>


		<array name="jdbc_url_parts">
			<item>db_schema</item>
			<item>db_host</item>
			<item>db_port</item>
			<item>db_name</item>
			<item>db_args</item>
		</array>

		<array name="supported_languages">
			<item>en</item>
			<item>ar</item>
		</array>

		<array name="table_users_columns_names">
			<item>id</item>
			<item>username</item>
			<item>email</item>
			<item>password</item>
			<item>admin</item>
		</array>

		<array name="table_users_columns_types">
			<item>int</item>
			<item>String</item>
			<item>String</item>
			<item>String</item>
			<item>boolean</item>
		</array>
	</class>


	<class name="html_classes" modifiers="public static">
		<key>account_help</key>
		<key>account_help_email_will_be_sent_container</key>
		<key>blank_space</key>
		<key>button</key>
		<key>button_container</key>
		<key>buttons_group</key>
		<key>captcha</key>
		<key>captcha_container</key>
		<key>container</key>
		<key>container_center</key>
		<key>dropdown_menu_close_button</key>
		<key>dropdown_menu_container</key>
		<key>dropdown_menu_content</key>
		<key>dropdown_menu_icon</key>
		<key>dropdown_menu_icon_container</key>
		<key>dropdown_menu_icons_container</key>
		<key>dropdown_menu_open_button</key>
		<key>dropdown_menus_group</key>
		<key>header_container</key>
		<key>header_separator</key>
		<key>input_container</key>
		<key>input_field_container</key>
		<key>login_and_register</key>
		<key>output_field_container</key>
		<key>password_toggle_icon</key>
		<key>remember_me</key>
		<key>search_bar_button</key>
		<key>search_bar_button_container</key>
		<key>search_bar_container</key>
		<key>search_bar_input</key>
		<key>text_field</key>
		<key>text_field_icons</key>
		<key>text_field_icons_container</key>
		<key>tooltip</key>
		<key>warning_messages_container</key>
	</class>


	<class name="html_ids" modifiers="public static">

		<key>admin_email</key>
		<key>admin_password</key>
		<key>admin_username</key>
		<key>captcha</key>
		<key>captcha_input</key>
		<key>captcha_output</key>
		<key>db_password</key>
		<key>db_url</key>
		<key>db_username</key>
		<key>email</key>
		<key>id</key>
		<key>output</key>
		<key>password</key>
		<key>register_email_regex</key>
		<key>register_password_regex</key>
		<key>register_username_regex</key>
		<key>username</key>
	</class>

	<class name="paths" modifiers="public static">
		<path name="mypth">files/db/current.dbd</path>
	</class>



</R>
